server:
  port: 7778
  servlet:
    context-path: /foodie-dev-api

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://1.14.140.53:30010/imooc_architect_04_microservice?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: jh541224

  redis:
#   redis集群配置
#    password: jh541224
#    cluster:
#      nodes: 1.14.140.53:7001,1.14.140.53:7002,1.14.140.53:7003,1.14.140.53:7004,1.14.140.53:7005,1.14.140.53:7006
#   redis 单机配置
    database: 1
    host: 1.14.140.53
    port: 30020
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    password: jh541224
#     redis 哨兵配置
#      database: 1
#      password: jh541224
#      sentinel:
#        master: mymaster
#        nodes: 1.14.140.53:26379,1.14.140.53:26380,1.14.140.53:26381
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl