server:
  port: 7778
  servlet:
    context-path: /foodie-user-service

spring:
  datasource:                                           # 数据源的相关配置
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  redis:
#   redis集群配置
#    password: jh541224
#    cluster:
#      nodes: 1.14.140.53:7001,1.14.140.53:7002,1.14.140.53:7003,1.14.140.53:7004,1.14.140.53:7005,1.14.140.53:7006
#   redis 单机配置
    database: 1
    host: ${redis.host}
    port: ${redis.port}
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    password: ${redis.password}
#     redis 哨兵配置
#      database: 1
#      password: jh541224
#      sentinel:
#        master: mymaster
#        nodes: 1.14.140.53:26379,1.14.140.53:26380,1.14.140.53:26381
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl